In [2]:
# BASIC NUMPY

In [3]:
# Single - dimensional array
import  numpy as np
n1 = np.array([10, 20, 30, 40])

In [5]:
n1

array([10, 20, 30, 40])

In [6]:
# Multi - dimension array
n2 = np.array([[1, 2, 3], [4, 5, 6]])
n2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# Initializing numpy array
n1 = np.zeros((2,3))
n1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
n2 = np.full((3, 3), 5)
n2

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [6]:
# Initilizing numpy array within a range
n1 = np.arange(10, 20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
n2 = np.arange(10, 50, 5)
n2

array([10, 15, 20, 25, 30, 35, 40, 45])

In [13]:
# Initilizing numpy array with random number
n1 = np.random.randint(1, 100, 5)
n1

array([43, 25, 50, 86,  3])

In [14]:
# NUMPY - SHAPE

In [15]:
# Checking the shape of numpy arrays
n1 = np.array([[1, 2, 3], [4, 5, 6]])
n1.shape

(2, 3)

In [18]:
n1.shape = (3, 2)
n1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
# JOINING NUMPY ARRAY
n1 = np.array([1, 2, 3])
n2 = np.array([4, 5, 6])

In [20]:
np.vstack((n1, n2))

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
np.hstack((n1, n2))

array([1, 2, 3, 4, 5, 6])

In [22]:
np.column_stack((n1, n2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [23]:
# NUMPY INTERSEVTION & DIFFERENCE
n1 = np.array([10, 20, 30, 40, 50, 60])
n2 = np.array([50, 60, 70, 80, 90])

In [28]:
np.intersect1d(n1, n2)

array([50, 60])

In [29]:
np.setdiff1d(n1, n2)

array([10, 20, 30, 40])

In [31]:
np.setdiff1d(n2, n1)

array([70, 80, 90])

In [32]:
# NUMPY ARRAY MATHEMATICS

# Addition of numpy arrays
n1 = np.array([10, 20])
n2 = np.array([30, 40])

In [33]:
np.sum([n1, n2])

100

In [35]:
np.sum([n1, n2], axis = 0)

array([40, 60])

In [36]:
np.sum([n1, n2], axis = 1)

array([30, 70])

In [38]:
# Basic addition
n1 = np.array([10, 20, 30])
n1 = n1 + 1
n1

array([11, 21, 31])

In [40]:
# Basic substraction
n1 = np.array([10, 20, 30])
n1 = n1 - 1
n1

array([ 9, 19, 29])

In [41]:
# Basic multiplication
n1 = np.array([10, 20, 30])
n1 = n1 * 2
n1

array([20, 40, 60])

In [42]:
# Basic divison
n1 = np.array([10, 20, 30])
n1 = n1 / 2
n1

array([ 5., 10., 15.])

In [43]:
# NUMPY MATH FUNCTION

# Mean
n1 = np.array([10, 20, 30, 40, 50, 60])
np.mean(n1)

35.0

In [45]:
# Median
n1 = np.array([11, 44, 30, 28, 6, 85])
np.median(n1)

29.0

In [46]:
# Stanad deviation
n1 = np.array([1, 5, 100, 28, 6, 48])
np.std(n1)

34.78345711525651

In [47]:
# NUMPY SAVE & LOAD
n1 = np.array([10, 20, 30, 40, 50])
np.save("myarray", n1)

In [48]:
n2 = np.load("myarray.npy")
n2

array([10, 20, 30, 40, 50])