# Basic Numpy Operations

In [3]:
# Single - dimensional array

import  numpy as np
n1 = np.array([10, 20, 30, 40])

In [4]:
n1

array([10, 20, 30, 40])

In [5]:
# Multi - dimension array

n2 = np.array([[1, 2, 3], [4, 5, 6]])
n2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# Initializing numpy array

n1 = np.zeros((2,3))
n1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
n2 = np.full((3, 3), 5)
n2

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [8]:
# Initilizing numpy array within a range

n1 = np.arange(10, 20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
n2 = np.arange(10, 50, 5)
n2

array([10, 15, 20, 25, 30, 35, 40, 45])

In [10]:
# Initilizing numpy array with random number

n1 = np.random.randint(1, 100, 5)
n1

array([36, 43, 70, 22, 93])

# NUMPY - SHAPE

In [11]:
# Checking the shape of numpy arrays

n1 = np.array([[1, 2, 3], [4, 5, 6]])
n1.shape

(2, 3)

In [12]:
n1.shape = (3, 2)
n1

array([[1, 2],
       [3, 4],
       [5, 6]])

# JOINING NUMPY ARRAY

In [16]:
n1 = np.array([1, 2, 3])
n2 = np.array([4, 5, 6])

In [17]:
np.vstack((n1, n2))

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np.hstack((n1, n2))

array([1, 2, 3, 4, 5, 6])

In [19]:
np.column_stack((n1, n2))

array([[1, 4],
       [2, 5],
       [3, 6]])

# NUMPY INTERSEVTION & DIFFERENCE

In [20]:
n1 = np.array([10, 20, 30, 40, 50, 60])
n2 = np.array([50, 60, 70, 80, 90])

In [22]:
np.intersect1d(n1, n2)

array([50, 60])

In [23]:
np.setdiff1d(n1, n2)

array([10, 20, 30, 40])

In [24]:
np.setdiff1d(n2, n1)

array([70, 80, 90])

# NUMPY ARRAY MATHEMATICS

In [26]:
# Addition of numpy arrays
n1 = np.array([10, 20])
n2 = np.array([30, 40])

In [27]:
np.sum([n1, n2])

100

In [28]:
np.sum([n1, n2], axis = 0)

array([40, 60])

In [29]:
np.sum([n1, n2], axis = 1)

array([30, 70])

In [30]:
# Basic addition
n1 = np.array([10, 20, 30])
n1 = n1 + 1
n1

array([11, 21, 31])

In [31]:
# Basic substraction
n1 = np.array([10, 20, 30])
n1 = n1 - 1
n1

array([ 9, 19, 29])

In [32]:
# Basic multiplication
n1 = np.array([10, 20, 30])
n1 = n1 * 2
n1

array([20, 40, 60])

In [33]:
# Basic divison
n1 = np.array([10, 20, 30])
n1 = n1 / 2
n1

array([ 5., 10., 15.])

# NUMPY MATH FUNCTION

In [34]:
# Mean
n1 = np.array([10, 20, 30, 40, 50, 60])
np.mean(n1)

35.0

In [35]:
# Mean
n1 = np.array([10, 20, 30, 40, 50, 60])
np.mean(n1)

35.0

In [36]:
# Median
n1 = np.array([11, 44, 30, 28, 6, 85])
np.median(n1)

29.0

In [37]:
# Stanad deviation
n1 = np.array([1, 5, 100, 28, 6, 48])
np.std(n1)

34.78345711525651

# NUMPY SAVE & LOAD

In [38]:
n1 = np.array([10, 20, 30, 40, 50])
np.save("myarray", n1)

In [39]:
n2 = np.load("myarray.npy")
n2

array([10, 20, 30, 40, 50])